# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TibetanAssistant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TibetanAssistant

  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'YYModel', '~> 1.0.4'
  pod 'Masonry', '~> 1.0.2'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'YBPopupMenu', '~> 1.1.2'

end
